### ISSUE TITLE
links from configuration file do show up on side in random order

### ISSUE THREAD

**Issue by Zugschlus** [spf13/herring-cove#12]
Hi,

this is an except from my config.yaml:
```
---
baseurl: "http://example.com/"
languageCode: "de"
title: "my Title"
theme: "herring-cove-master"                                                            
params:                                                                                 
  ProfilePicture: "bilder/20140819-Fassade.jpg"                                         
   links:                                                                                
    Startseite: ""                                                                      
    Grundrisse: "grundrisse"                                                            
    Außen: "aussen"                                                                     
    Erdgeschoss: "eg"
    Obergeschoss: "og"
    Dachgeschoss: "dg"
    Kellergeschoss: "kg"
    Garten: "garten"
    Technik: "technik"
    Leimen: "leimen"
    Mieten: "mieten"
    Impressum: "impressum"
```

The links show up in the left site navigation column fine, but they show up in random order that even changes when new items are added or removed. I would like to have the links show up in exactly the order specified in the config file.

Is there any way to achive that?

Greetings
Marc
